config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  ActiveAdmin.routes(self)
  
  root 'welcome#index'
  get 'welcome/index'
  get 'welcome/add_detail'

end

app/models/detail.rb
class Detail < ActiveRecord::Base
  
  do_not_validate_attachment_file_type :photo
  validates_presence_of :title, :start_date, :end_date, :photo, :description 
  
  has_many :user_details
  has_many :users, through: :user_details
  has_attached_file :photo,
                    :styles => {:original => "400x600>", :thumb => "120x120>" },  
                    :path => ":rails_root/public/:class/:attachment/:id/:style/:filename",
                    :url => "/:class/:attachment/:id/:style/:filename"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :user_details
  has_many :details, through: :user_details
  
  def self.find_for_database_authentication(conditions={})
    find_by(email: conditions[:email]) || find_by(phone: conditions[:email])
  end
  
  def detail_added? detail
    self.details.include? detail
  end
  
end

app/models/user_detail.rb
class UserDetail < ActiveRecord::Base
  belongs_to :user
  belongs_to :detail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def authenticate_active_admin_user!
    authenticate_user!
    unless current_user.admin?
      flash[:alert] = "Unauthorized Access!"
      redirect_to root_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_action :authenticate_user!, only:[:add_detail]
  
  def index
    @details = Detail.paginate(page: params[:page], per_page: 10)
  end
  
  def add_detail
    detail = Detail.find(params[:id])
    current_user.user_details.create(detail: detail)
    flash[:success] = 'Added successfully!'
    redirect_to root_path
  end
  
  private
    def authenticate_user!
      redirect_to new_user_session_path unless user_signed_in?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default">      
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'GET CAMPUS', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>  
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GetCampus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class=" col-xs-10 col-xs-10 col-xs-10 col-md-offset-1">
        <%= render "layouts/header" %>
        <%= render 'layouts/messages' %>             
        <%= yield %>
      </div>
    </div>    
  </div>
</body>
</html>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12">
    <h4 class="form-title"></h4>
    <% @details.each do |detail| %>
      <div class="main-detail">
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="detail-title"><%= detail.title %></div><br/>
            <div class="start-end-date"><%= detail.start_date.strftime("%d/%m/%Y") %> to <%= detail.end_date.strftime("%d/%m/%Y") %></div>
          </div>
        </div>  
        <div class="row">
          <div class="col-md-12 description"><%= detail.description.html_safe %></div>
          <div class="col-md-12">
            <% if current_user && current_user.detail_added?(detail) %>
              <%= link_to "Applied", "#", class: "btn btn-info text-bold disabled pull-right"%>
            <% else %>
              <%= link_to "Apply", welcome_add_detail_path(id: detail.id), class: "btn btn-primary text-bold pull-right "%>
            <% end %>
          </div>
        </div>     
      </div>  
    <% end %>  
  </div>
</div>

<%= will_paginate @details, renderer: BootstrapPagination::Rails %>